dist: trusty
sudo: false
language: java
jdk:
  - oraclejdk8
addons:
  postgresql: 9.6
  apt:
    packages:
      - oracle-java8-installer
before_script:
  - mvn versions:display-dependency-updates versions:display-plugin-updates
  - psql -c 'create database mtsar;' -U postgres
  - java -jar target/mtsar.jar db migrate environment.yml.travis
  - mvn clean
env:
  - MTSAR_TEST_YAML=environment.yml.travis
cache:
  directories:
    - $HOME/.m2
