postgresdata:
  image: postgres
  volumes:
    - /var/lib/postgresql
  command: tail -f /dev/null
postgres:
  image: postgres
  environment:
    POSTGRES_USER: mtsar
    POSTGRES_PASSWORD: mtsar
  volumes_from:
    - postgresdata
  expose:
    - 5432
app:
  image: mtsar
  ports:
    - "8080:8080"
    - "8081:8081"
  links:
    - postgres
